steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/mlops-project-411316/training:latest', 'mlops_group_17/dockerfiles/train_model.dockerfile']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/mlops-project-411316/training:latest']
options:
  logging: 'CLOUD_LOGGING_ONLY'

