# hyperparameters for training the model

shuffle: True
batch_size: 64
learning_rate: 0.003
epochs: 10
weight_decay: 0.0005
dropout_rate: 0.5
processed_dataset: "../data/processed/"
dataset_name: 'Apple Pink Lady'

