name: "Run tests"

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      KAGGLE_CREDENTIALS: ${{ secrets.KAGGLE_CREDENTIALS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.10.13
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.13
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_tests.txt
      - name: Test with pytest
        run: |
          pip install pytest
          pytest -v
